### ISSUE TITLE
Version 2.6.0

### ISSUE THREAD

**Issue by stavros-zavrakas** [OpenVidu/openvidu-call-react#1]
It seems that the version 2.6.0 is not properly published on npm. You did a fix on gituhub to use the componentWillUnmount lifecycle hook instead of the componentDidUnmount that does not exist. Can you double check that?

**Comment by CSantosM** [comment]
This fix will be published in the next release.

**Comment by stavros-zavrakas** [comment]
@CSantosM When is this going to be? We have some issues with the conferences
