### ISSUE TITLE
There aren't latest features which have in anguler repository

### ISSUE THREAD

**Issue by turdiyev** [OpenVidu/openvidu-call-react#11]
Hello react team.
Do you have plan to develop similar to angular proeject?

**Comment by CSantosM** [comment]
Hello @turdiyev ,

Please use issue tracker only for issues, you can use the [OpenVidu forum](https://openvidu.discourse.group/) instead. 

Anyway, regarding your question, it’s not in our roadmap at the moment. 

Regards
