### ISSUE TITLE
React 17

### ISSUE THREAD

**Issue by jfvilasat** [OpenVidu/openvidu-call-react#21]
Hi there.

I'm testing this react library in order to add webrtc capabilities to a hybrid mobile application. As far as I know, the highest version of this library has a dependency on 16. Am I mistaken? If not... have you plans to build a release of the library for react 17? Thanks in advance.

**Comment by CSantosM** [comment]
Hi, our mate @ash0x0 is working on an tutorial update. He contributed to this project with a PR https://github.com/OpenVidu/openvidu-call-react/pull/20 and he's fixing some little details.

**Comment by jfvilasat** [comment]
Thank you very much!!

**Comment by ash0x0** [comment]
I'll make sure to change that. I tried it and I don't notice anything breaking (17 has almost no breaking changes) so if you're in a rush you can do it in your app because I'm still not done with that PR.

**Comment by jfvilasat** [comment]
I'm not in a rush. I'm just working with 16 without a problem.

Very appreciated help!!
